<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>

<div id="welcome">
    <h3>Listado de productos</h3>

    <ul class="list">
    <?php foreach($this->products as $product): ?>
      <li>
        <span>
          <a href="/index/update/productid<?php echo $product->productCode; ?>"><?php echo $product->productCode; ?></a>
        </span> -
        <span><?php echo $product->productName; ?></span> -
        <span><?php echo $product->productDescription; ?></span>
      </li>
    <?php endforeach ?>
    </ul>
</div>